---
- hosts: all
  gather_facts: true
  connection: local

  vars:
    java_maj_ver: 8
    java_min_ver: 312
    home_dir: /home/vagrant
   
        
- name: Install openjdk java
  hosts: all
  roles:
    - role: lean_delivery.java
      transport: repositories
      java_major_version: 8
      java_minor_version: 312